{{- if .Values.ingresscf.enabled -}}
{{- $fullName := include "timeoff-management-app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingresscf.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingresscf.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingresscf.annotations "kubernetes.io/ingress.class" .Values.ingresscf.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $fullName }}-cf"
  labels:
    {{- include "timeoff-management-app.labels" . | nindent 4 }}
  {{- with .Values.ingresscf.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingresscf.ingressClassName }}
  ingressClassName: {{ .Values.ingresscf.ingressClassName }}
  {{- end }}
  {{- if .Values.ingresscf.tls }}
  tls:
    {{- range .Values.ingresscf.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingresscf.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
