apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timeoff-management
  namespace: argocd
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/timeoff-management
spec:
  destination:
    namespace: timeoff-management
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/helm/timeoff-management-app
    repoURL: https://github.com/enzojimenez/timeoff-management-application.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m0s
      limit: 2
