apiVersion: v1
kind: Service
metadata:
  name: timeoff-management-app-godaddy
  namespace: timeoff-management
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nlb.time.in10minutes.dev
  labels:
    {{- include "timeoff-management-app.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "timeoff-management-app.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-staging
  name: timeoff-management-app-godaddy
  namespace: timeoff-management
spec:
  ingressClassName: nginx
  rules:
  - host: timeoff-management-app.in10minutes.dev
    http:
      paths:
      - backend:
          service:
            name: timeoff-management-app-godaddy
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - timeoff-management-app.in10minutes.dev
    secretName: timeoff-management-app-in10minutes-dev-tls
